version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: PYTHONPATH=~/src; export PYTHONPATH; pwd;ls $PYTHONPATH;printenv;python -m pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
