version: 2.1

executors:
  exectr:
    docker:
      - image: guycole/cpp-dev:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup gtest child repo
          command: |
            cd ferretdlib
            git submodule init
            git submodule update 
      - run:
          name: setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: build

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: execute tests
          command: |
            cd build
            ./gtestbin --gtest_output=XML
      - store_test_results:
          path: build

  workflows:
    version: 2

    workflow:
      jobs:
        - build
        - test:
            requires:
              - build
