version: 2.1

jobs:
  build-and-test:
    working_directory: ~/mellow-ferret

    docker:
      - image: circleci/python:3.8.2
        environment:
          BOGUS: YADDA

    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest
          name: Test
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - build-and-test
