# tune to KQED FM
#
# unique installation identifier
installationId: 820d1021-75d6-4c83-8487-edbe4b433858
#
# mandatory initialization
commands:
  # memory clear
  - AC
  # print version
  - VR
  # tune to KQED
  - RF88.5M
  #
  - MD00
  #
  - AT
  #
  - RM 
  #